### ISSUE TITLE
Unable to connect within docker network

### ISSUE THREAD

**Issue by gkaino** [rstudio/plumber#485]
### Problem
Unable to connect within docker network.
Starting python and R containers with docker-compose.
I want to access R from a python container

Cannot connect both of the following
```
api$run(host="0.0.0.0",port=4177)
```
or
```
api$run(port=4177)
```

If you open the port in the docker-compose settings, you can access with the host IP.

I want to be able to access by http://[container name] or http://localhost from python container.

### code

R
run.r
```
require(plumber)
api <- plumb("test.r")
api$run(host="0.0.0.0",port=4177)
```
test.r
```
#* @get /init
function(){
  require(forecast)
}
```

python
run.py
```
import requests
url='http://localhost:4177/init'  
params = {'Accept': 'application/json; charset=UTF-8'}
ret = requests.get(url,headers=params) 
```

docker-compose file
```
version: "2.4"

services:

  py_api:
    image:
      api_image:latest
    container_name: 
      py_api
    ports:
      - 4178:4178

    volumes:
      - /home/gen/test:/workspace
    command:
      python /workspace/run.py
    depends_on:
      r_api:
        condition: service_started


  r_api:
    image:
      api_image:latest
    container_name: 
      r_api
      
#    ports:
#      - 4177:4177

    volumes:
      - /home/gen/test:/workspace
    command:
      Rscript /workspace/run.r
```

Dockerfile  (docker build -t api_image .)
```
FROM continuumio/anaconda3:2019.03
RUN apt-get update && apt-get install -y --no-install-recommends build-essential r-base r-cran-randomforest
RUN R -e "install.packages(c('plumber','reticulate','data.table','forecast','lubridate','dplyr'),dependencies=TRUE,repos='http://cran.rstudio.com/')"
RUN python --version
RUN pip install --upgrade pip
RUN pip install mpl_finance
RUN pip install light-progress
RUN pip install redis
RUN pip install flask_cors
RUN mkdir /workspace
```
