### ISSUE TITLE
parameter default values for Swagger

### ISSUE THREAD

**Issue by bhogan-mitre** [rstudio/plumber#523]
The documentation nicely describes default values for the handling functions that are behind the endpoints, but those are not carried through to the Swagger interface.  A user could submit the form without a parameter value and the default would be applied behind the scenes, _but they would not know that from looking at the interface_. 

It would be useful to carry through the default values into Swagger.  I believe that data would need to be provided in the `schema` [here](https://github.com/rstudio/plumber/blob/master/R/swagger.R#L145-L153):
```
    paramList <- list(
      name = p,
      description = endpointParams[[p]]$desc,
      `in` = location,
      required = endpointParams[[p]]$required,
      schema = list(
        type = type
      )
    )
```

Here's an example per the [Swagger documentation](https://swagger.io/docs/specification/describing-parameters/)
```
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
          required: false
          description: The number of items to skip before starting to collect the result set.
```

Thanks for considering.
