### ISSUE TITLE
Param schema definitions

### ISSUE THREAD

**Issue by kempspo** [rstudio/plumber#818]
It would be useful to be able to add a more flexible schema definition of the parameters. Such as being able to add the accepted values of the parameter on the Swagger interface. 

I believe the change would be in the schema [here](https://github.com/rstudio/plumber/blob/3d0c4ae8b62a62b5bb6b363a83e8f52889c72a2e/R/openapi-spec.R#L166-L174)
```  
paramList <- list(
        name = p,
        description = endpointParams[[p]]$desc,
        `in` = location,
        required = required,
        schema = list(
          type = type,
          format = apiTypesInfo[[type]]$format,
          default = funcParams[[p]]$default
```
Here's an example per [OpenAPI documentation](https://swagger.io/docs/specification/describing-parameters/)

```
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum:
              - available
              - pending
              - sold
```
