### ISSUE TITLE
Schema Definitions

### ISSUE THREAD

**Issue by kempspo** [rstudio/plumber#819]
Definitely useful to be able to define the schema of our objects, [like so](https://swagger.io/docs/specification/components/). Found it particularly hard to communicate POST body request formats without having to talk to other devs directly and figure out how it was built. 

```
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
```
