### ISSUE TITLE
Request from plumber API returning "error":["405 - Method Not Allowed"] on browser in Docker Swarm Deploy

### ISSUE THREAD

**Issue by gabrielteotonio** [rstudio/plumber#838]
Hi, I'm testing Plumber with Docker Swarm and getting the following error when requesting from browser  
`{"error":["405 - Method Not Allowed"]}`,  
But if I go to `~/___docs__/` I can access Swagger UI and execute requests, receiving the proper response.

I did tests with the function that I'm exposing in the api running a standalone container from the `rstudio/plumber` image and I had no problems. I was also able to get a response from the api making requests from my local terminal through `curl -X POST`.

Files used to generate the service in Docker Swarm 👇🏼 

`.yml` file:
```
version: "3"

services:

  api:
    image: rstudio/plumber:v1.0.0
    command: /app/plumber.R
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    deploy:
      restart_policy:
        condition: on-failure
```
`app/plumber.R` file:
```
#* Return the sum of three numbers
#* @param a The first number to add
#* @param b The second number to add
#* @param c The third number to add
#* @post /sum
function(a, b, c) {
  as.numeric(a) + as.numeric(b) + as.numeric(c)
}
```

To deploy the service in Docker Swarm:
```
docker swarm init
docker stack deploy -c docker-stack-plumber.yml plumber
```
